version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  remote_db:
    image: postgres
    restart: always
    # entrypoint: docker-entrypoint.sh
    # command: |-
    #   chmod +x _scripts/remote_pq_db_initializer.sh
    #   ./_scripts/remote_pq_db_initializer.sh
    volumes:
      - ./tmp/remote_db:/var/lib/postgresql/data
      - ./_scripts:/_scripts
  ms_db:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
    - ./tmp/ms_db:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_SA_PASSWORD:-yourStrong(!)Password}
    ports:
      - "1433:1433"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/dashboardr
    ports:
      - "3000:3000"
    depends_on:
      - db
      - remote_db
      - ms_db