version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  remote_db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/remote/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/dashboardr
    ports:
      - "3000:3000"
    depends_on:
      - db
      - remote_db